name: neuris
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - bzip2
  - ca-certificates
  - ffmpeg
  - freetype
  - giflib
  - jpeg
  - lame
  - libffi
  - libpng
  - libtiff
  - libwebp
  - ncurses
  - openh264
  - openssl
  - pillow
  - pip
  - python=3.8
  - pyyaml
  - readline
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - backcall==0.2.0
      - blinker==1.8.2
      - cachetools==5.5.2
      - click==8.1.8
      - colorama==0.4.6
      - comm==0.2.2
      - configargparse==1.7.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - dash==3.1.1
      - decorator==5.2.1
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - flask==3.0.3
      - fonttools==4.57.0
      - freetype-py==2.5.1
      - fsspec==2025.3.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - icecream==2.1.0
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipython==8.12.3
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - llvmlite==0.39.1
      - lpips==0.1.4
      - mako==1.3.10
      - markdown==3.7
      - matplotlib==3.6.3
      - matplotlib-inline==0.1.7
      - narwhals==1.42.1
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numba==0.56.4
      - numpy==1.19.2
      - oauthlib==3.3.1
      - open3d==0.19.0
      - opencv-python==4.5.2.52
      - packaging==25.0
      - pandas==1.4.4
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==6.2.0
      - prompt-toolkit==3.0.51
      - protobuf==5.29.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycuda==2025.1.1
      - pyglet==2.1.6
      - pygments==2.19.2
      - pyhocon==0.3.57
      - pymcubes==0.1.2
      - pyopengl==3.1.0
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - pytools==2024.1.14
      - pytz==2025.2
      - pywavelets==1.4.1
      - referencing==0.35.1
      - requests-oauthlib==2.0.0
      - retrying==1.4.0
      - rpds-py==0.20.1
      - rsa==4.9.1
      - scikit-image==0.19.3
      - scikit-learn==1.3.2
      - scipy==1.7.0
      - setuptools==59.5.0
      - six==1.17.0
      - stack-data==0.6.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - torch==2.4.1
      - tqdm==4.50.2
      - traitlets==5.14.3
      - trimesh==3.9.8
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - zipp==3.20.2
